# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_auto_20170715_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenproducto',
            options={'verbose_name': 'Imagen de producto', 'verbose_name_plural': 'Imágenes de producto'},
        ),
    ]
